extends SceneTree
## Godot --headless --path . --script tools/save_building_collisions.gd -- /tmp/hks-collisions

func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	if args.size() != 1:
		push_error("Pass the directory generated by build_building_collisions.py")
		quit(1)
		return
	var output := "res://assets/collisions/buildings"
	DirAccess.make_dir_recursive_absolute(output)
	for filename in DirAccess.get_files_at(args[0]):
		if filename.ends_with(".tres"):
			var shape := load(args[0].path_join(filename)) as ConcavePolygonShape3D
			if shape == null or ResourceSaver.save(shape, output.path_join(filename.get_basename() + ".res"), ResourceSaver.FLAG_COMPRESS) != OK:
				quit(1)
				return
	DirAccess.copy_absolute(args[0].path_join("manifest.json"), output.path_join("manifest.json"))
	quit()
